import type { Metadata } from "next";
import Link from "next/link";
import { DocsPagination } from "@/components/docs/DocsPagination";
import { DocsCallout } from "@/components/docs/DocsCallout";

export const metadata: Metadata = {
  title: "Reliability & Architecture",
  description:
    "System reliability, bounded execution limits, structured schema enforcement, and fail-closed safety in Verdict.",
};

export default function ReliabilityPage() {
  const pillars = [
    {
      title: "Strict Bounded Execution",
      desc: "Every audit executes within deterministic character and page gathering budgets. This guarantees predictable completion times (60–90s) and prevents runaway scraping loops.",
    },
    {
      title: "Structured Schema Validation",
      desc: "All LLM outputs are validated against strict JSON schemas. If a model output deviates from the expected schema, it is retried and validated before persisting, preventing corrupt records.",
    },
    {
      title: "Deterministic Scoring Authority",
      desc: "The overall Growth Readiness Score is calculated in code via fixed mathematical formulas rather than generated by an unconstrained LLM prompt, guaranteeing consistency.",
    },
    {
      title: "Fail-Closed Relevance Gating",
      desc: "If a supporting page's relevance to the audited company cannot be verified due to network errors or ambiguity, Verdict fails closed and discards the page from scoring.",
    },
  ];

  return (
    <div className="space-y-12">
      {/* Header */}
      <div className="space-y-3">
        <p className="font-mono text-[12px] font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500">
          Trust
        </p>
        <h1 className="text-3xl font-extrabold tracking-tight text-slate-950 dark:text-white sm:text-4xl">
          Reliability & Architecture
        </h1>
        <p className="text-lg leading-relaxed text-slate-600 dark:text-slate-300 pt-1">
          Verdict is engineered as a robust, deterministic growth intelligence engine rather than
          a brittle prompt wrapper.
        </p>
      </div>

      {/* Pillars Grid */}
      <section className="space-y-4">
        <h2 className="text-xl font-bold text-slate-950 dark:text-white">
          Reliability Guarantees
        </h2>
        <div className="grid gap-4 sm:grid-cols-2 pt-2">
          {pillars.map((item) => (
            <div
              key={item.title}
              className="rounded-2xl border border-slate-200/80 bg-white p-5.5 dark:border-slate-800/80 dark:bg-slate-900/40 shadow-xs space-y-2"
            >
              <h3 className="text-sm font-bold text-slate-950 dark:text-white">
                {item.title}
              </h3>
              <p className="text-xs leading-relaxed text-slate-600 dark:text-slate-400">
                {item.desc}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Section: Model Resilience */}
      <section className="space-y-4 pt-4 border-t border-slate-200/80 dark:border-slate-800/80">
        <h2 className="text-xl font-bold text-slate-950 dark:text-white">
          Model Failover & Timeout Discipline
        </h2>
        <p className="text-[15px] leading-relaxed text-slate-600 dark:text-slate-300">
          The investigation pipeline enforces rigid timeout budgets across all HTTP extraction
          and model execution tasks. If an individual stage encounters transient model latency,
          the system degrades gracefully, maintaining audit progress without stalling the consumer.
        </p>

        <DocsCallout type="note" title="Zero Telemetry Leakage">
          Even during internal failover or retry routines, Verdict preserves strict privacy: internal
          diagnostics are logged privately, and external consumers receive clean, sanitized HTTP status codes.
        </DocsCallout>
      </section>

      <DocsPagination
        prev={{
          title: "Payments",
          href: "/docs/payments",
          description: "Human quotas and agent payment rails.",
        }}
        next={{
          title: "Scoring methodology",
          href: "/docs/scoring-methodology",
          description: "Mathematical weighting and rubric tiers.",
        }}
      />
    </div>
  );
}
